# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17YbPRzOISHDVHL-9mbDxwNLKCRcB9RXe
"""

# prompt: now code a file that take the file and give prediction on streamlit app
import streamlit as st
import pickle
import pandas as pd

# Load the trained model
loaded_model = pickle.load(open("finalized_model.sav", 'rb'))

# Function to predict spending score
def predict_spending_score(income, monthly_purchases):
    new_data = pd.DataFrame({'Income': [income], 'Monthly_Purchases': [monthly_purchases]})
    prediction = loaded_model.predict(new_data)
    return prediction[0]

# Streamlit app code
st.title("Spending Score Prediction")

income = st.number_input("Enter income:")
monthly_purchases = st.number_input("Enter monthly purchases:")

if st.button('Predict'):
    spending_score = predict_spending_score(income, monthly_purchases)
    st.write(f"Predicted Spending Score: {spending_score}")

